dict1= {[0,0],[0,1],[0,2],
       [1,0],[1,1],[1,2],
       [2,0],[2,1],[2,2]} 3x3 array

In [1]:
for x in range(1,4):
    print(x)

1
2
3


In [12]:
class games(): #defining the class as games (planned to use more than 1 game)
    
    def __init__(self,P1,P2,z1,z2): #__init__ to setup the variables going to be used
        self.P1 = int(P1)
        self.P2 = int(P2)
        self.z1 = int(z1)
        self.z2 = int(z2)
        
    def tictactoe(self): #define the tictactoe game
        def win(self):
            return ((ttt[0][0]==ttt[0][1]==ttt[0][2]==self.z1 or
                ttt[1][0]==ttt[1][1]==ttt[1][2]==self.z1 or
                ttt[2][0]==ttt[2][1]==ttt[2][2]==self.z1 or
                ttt[0][0]==ttt[1][1]==ttt[2][2]==self.z1 or
                ttt[0][2]==ttt[1][1]==ttt[2][0]==self.z1 or
                ttt[0][0]==ttt[1][0]==ttt[2][0]==self.z1 or
                ttt[0][1]==ttt[1][1]==ttt[2][1]==self.z1 or
                ttt[0][2]==ttt[1][2]==ttt[2][2]==self.z1 or
                ttt[0][0]==ttt[0][1]==ttt[0][2]==self.z2 or
                ttt[1][0]==ttt[1][1]==ttt[1][2]==self.z2 or
                ttt[2][0]==ttt[2][1]==ttt[2][2]==self.z2 or
                ttt[0][0]==ttt[1][1]==ttt[2][2]==self.z2 or
                ttt[0][2]==ttt[1][1]==ttt[2][0]==self.z2 or
                ttt[0][0]==ttt[1][0]==ttt[2][0]==self.z2 or
                ttt[0][1]==ttt[1][1]==ttt[2][1]==self.z2 or
                ttt[0][2]==ttt[1][2]==ttt[2][2]==self.z2 or
                (ttt.all()!=0) and (ttt.any()!=0)))
    #rows, columns, crosses for 1st and 2nd variable.
        count=0 #start the count at 0 turn.
        print(ttt) #print the array
        while win(self)==False: #start the while loop
            if count%2==self.P1: #my turn
                 while count%2==self.P1:
                    x = int(input("Enter row (1/2/3)"))
                    y = int(input("Enter column (1/2/3)"))            
                    if x not in range(1,4) or y not in range(1,4):
                        print("You can't enter numbers outside of 1,2, and 3")
                    elif ttt[x-1][y-1]!=0:
                        print("You can't change an already previously filled box. Don't cheat!")
                    else: 
                        ttt[x-1][y-1]=self.z1
                        print(ttt)
                        count+=1
                        print("Turns:",count)     
            else: #computer's turn
                while count%2!=self.P1:
                    x= rand.randint(1,3)
                    y= rand.randint(1,3)
                    if ttt[x-1][y-1]!=0:
                        print("I'm thinking")
                    else: 
                        ttt[x-1][y-1]=self.z2
                        print(ttt)
                        count+=1
                        print("Turns:",count)
        if ttt.all()!=0: #condition for draw
            print("It's a draw.")
        elif count%2!=self.P1: #condition for user's win
            print("You won!")
        else: #condition for cpu's win
            print("I won!")

In [17]:
import random as rand
import numpy as np
count = 0
print("Turns:",count)
ttt = np.zeros((3,3)) #set up the array
print(ttt) #show the array
v=2
z1=0
z2=0
while (z1==0 or z2==0) or (z1==z2): #make sure the input is within reason
    z1= int(input("Enter number you want to use: "))
    z2= int(input("Enter number you want computer to use: "))
    if z1==0 or z2==0:
        print("Can't use number for 'blanks'. This is considered cheating.")
    elif z1==z2: 
        print("Computer can't use same number as you.")
    else:
        while v!=0 and v!=1: #make sure the input is within reason
            v = int(input("Do you want to go first? (1=Y/0=N) "))
            if v!=0 and v!=1: #output if it's an unreasonable input
                print("Please enter (1/0)")
            elif v == 1: #
                g1= games(0,1,z1,z2)
                g1.tictactoe()
            else:
                g1=games(1,0,z1,z2)
                g1.tictactoe()


Turns: 0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Enter number you want to use: 1
Enter number you want computer to use: 1
Computer can't use same number as you.
Enter number you want to use: 1
Enter number you want computer to use: 2
Do you want to go first? (1=Y/0=N) 1
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Enter row (1/2/3)1
Enter column (1/2/3)1
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Turns: 1
[[1. 0. 0.]
 [0. 0. 2.]
 [0. 0. 0.]]
Turns: 2
Enter row (1/2/3)1
Enter column (1/2/3)2
[[1. 1. 0.]
 [0. 0. 2.]
 [0. 0. 0.]]
Turns: 3
[[1. 1. 0.]
 [0. 2. 2.]
 [0. 0. 0.]]
Turns: 4
Enter row (1/2/3)1
Enter column (1/2/3)3
[[1. 1. 1.]
 [0. 2. 2.]
 [0. 0. 0.]]
Turns: 5
You won!
